services:
  postgres:
    image: postgres:16
    container_name: fsa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsa_assignment
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
